# Implement PCA using scikit-learn

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [4]:
# --------------------------------------------
# Step 1: Original Dataset
# --------------------------------------------

employees = ["A", "B", "C", "D", "E"]

X = np.array([
    [2, 65, 70],
    [4, 80, 78],
    [5, 85, 82],
    [6, 90, 88],
    [8, 98, 95]
])

print("Original Dataset")
print(X)

Original Dataset
[[ 2 65 70]
 [ 4 80 78]
 [ 5 85 82]
 [ 6 90 88]
 [ 8 98 95]]


In [5]:
# --------------------------------------------
# Step 2: Standardised the data
# --

scaler = StandardScaler()
X_std = scaler.fit_transform(X)

print("\n Standardized dataset")
print(np.round(X_std, 4))


 Standardized dataset
[[-1.5    -1.6851 -1.4784]
 [-0.5    -0.3261 -0.5397]
 [ 0.      0.1268 -0.0704]
 [ 0.5     0.5798  0.6336]
 [ 1.5     1.3046  1.4549]]


Minor differences may occur because Python retains full floating-point precisions, whereas, the manual calculations were rounded to four decimal places

In [7]:
# --------------------------------------------
# Step 3: Perform the PCA
# --

pca = PCA(n_components = 3) # number of target dimensions or the principal components to keep after reducing the dataset's size
X_pca = pca.fit_transform(X_std)


# --------------------------------------------
# Step 4: Display PCA Results
# --------------------------------------------

print("\nEigenvalues")
print(np.round(pca.explained_variance_, 6))

print("\nExplained Variance Ratio")
print(np.round(pca.explained_variance_ratio_, 6))

print("\nPrincipal Components (Eigenvectors)")
print(np.round(pca.components_, 6))

print("\nReduced Dataset")
print(np.round(X_pca, 4))


Eigenvalues
[3.724617e+00 2.223400e-02 3.149000e-03]

Explained Variance Ratio
[9.93231e-01 5.92900e-03 8.40000e-04]

Principal Components (Eigenvectors)
[[ 0.578344  0.575893  0.57781 ]
 [-0.330663  0.812973 -0.479308]
 [ 0.745775 -0.086145 -0.660605]]

Reduced Dataset
[[-2.6922e+00 -1.6530e-01  3.1000e-03]
 [-7.8890e-01  1.5890e-01  1.1800e-02]
 [ 3.2400e-02  1.3690e-01  3.5600e-02]
 [ 9.8920e-01  2.4000e-03 -9.5600e-02]
 [ 2.4595e+00 -1.3280e-01  4.5200e-02]]


Comparison: The eigenvalues obtained using scikit-learn differ from the manually computed values because the manual solution used a normalised covariance (correlation) matrix with unit variances, whereas scikit-learn computes PCA using the sample covariance matrix of the standardised data. Consequently, the Python eigenvalues are scaled by a constant factor. Despite this difference, both approaches identify the same dominant principal component, and the explained variance ratios and overall conclusions remain consistent